columns:
  - Item_Identifier : object
  - Item_Weight : float64
  - Item_Fat_Content : object
  - Item_Visibility : float64
  - Item_Type : object 
  - Item_MRP : float64
  - Outlet_Identifier: object
  - Outlet_Establishment_Year : object
  - Outlet_Size : object
  - Outlet_Location_Type : object
  - Outlet_Type : object
  - Item_Outlet_Sales : float64

numerical_columns :
  - Item_Weight
  - Item_Visibility
  - Item_MRP
  - Outlet_Establishment_Year
  - Item_Outlet_Sales

numeric_columns:
  - Item_Weight
  - Item_Visibility
  - Item_MRP
  - Outlet_Establishment_Year

onehot_columns :
  - Item_Fat_Content
  - Item_Type 
  - Outlet_Identifier
  - Outlet_Size
  - Outlet_Location_Type
  - Outlet_Type

ordinal_columns :
  - Item_Identifier

drop_columns:
