columns:
  - Item_Identifier : category
  - Item_Weight : float
  - Item_Fat_Content : category
  - Item_Visibility : float
  - Item_Type : category 
  - Item_MRP : float
  - Outlet_Identifier: category
  - Outlet_Establishment_Year : int
  - Outlet_Size : category
  - Outlet_Location_Type : category
  - Outlet_Type : category
  - Item_Outlet_Sales : float

numerical_columns :
  - Item_Weight : float
  - Item_Visibility : float
  - Item_MRP : float
  - Outlet_Establishment_Year : int
  - Item_Outlet_Sales : float

drop_columns:
