columns:
# - Item_Identifier
# - Item_Weight
# - Item_Fat_Content
# - Item_Visibility
# - Item_Type
# - Item_MRP
# - Outlet_Identifier
# - Outlet_Establishment_Year
# - Outlet_Size
# - Outlet_Location_Type
# - Outlet_Type
# - Item_Outlet_Sales
  - Item_Identifier : category
  - Item_Weight : float
  - Item_Fat_Content : category
  - Item_Visibility : float
  - Item_Type : category 
  - Item_MRP : float
  - Outlet_Identifier: category
  - Outlet_Establishment_Year : int
  - Outlet_Size : category
  - Outlet_Location_Type : category
  - Outlet_Type : category
  - Item_Outlet_Sales : float

numerical_columns :
  - Item_Weight
  - Item_Visibility
  - Item_MRP
  - Outlet_Establishment_Year
  - Item_Outlet_Sales

drop_columns:
